#!/usr/bin/env python3
"""Generates the two shared language-switcher assets:

  assets/css/lang-flags.css  flag styling + the inline-SVG fallback used where
                             regional-indicator emoji do not render
  assets/js/lang.js          the entry-time language detector and the
                             flag-emoji capability probe

Why a separate stylesheet instead of inlining the SVGs in every page:
143 pages x ~11KB of flag data URIs would be ~1.5MB of duplicated markup, and
the flags are identical on every page. One extra small stylesheet, fetched in
parallel with style.css and cached across the whole site, is the cheaper trade.

Why not fold the rules into assets/css/style.css: these are GENERATED, and
style.css is hand-maintained. Rewriting a region of a hand-maintained file on
every build is how a build script eats someone else's edit.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from flag_svgs import FLAG_EMOJI, data_uri  # noqa: E402
from site_common import LANGUAGES, ROOT  # noqa: E402
import lang_detect  # noqa: E402

CSS_OUT = ROOT / "assets" / "css" / "lang-flags.css"
JS_OUT = ROOT / "assets" / "js" / "lang.js"

HEAD = """/* GENERATED by scripts/build_lang_assets.py — do not edit by hand.
   Re-run `python3 scripts/build.py` (or that script alone) after changing
   scripts/flag_svgs.py.

   The switcher renders a flag EMOJI. That is correct everywhere the platform
   composes regional-indicator pairs: macOS, iOS, Android, most Linux, and
   Firefox on Windows (which ships its own emoji font). Chrome and Edge on
   Windows fall back to Segoe UI Emoji, which contains no flag glyphs at all,
   so the pair renders as two letter-boxes reading "GB" / "JP" / "DE".

   The inline <head> detector in scripts/site_common.py measures whether a
   regional-indicator pair composes to one glyph and, when it does not, sets
   `no-flag-emoji` on <html> BEFORE first paint. Everything below that class
   swaps the emoji for a drawn SVG. Nothing here runs without that class, so
   the emoji stays primary and this is pure fallback. */

.lang-flag {
  flex: none;
  line-height: 1;
  margin-inline-end: 8px;
  /* Emoji presentation, not the text-style variant some fonts default to. */
  font-family: "Apple Color Emoji", "Segoe UI Emoji", "Noto Color Emoji",
               "Twemoji Mozilla", "Android Emoji", sans-serif;
  font-size: 1.05em;
}
.lang-switch__toggle .lang-flag { margin-inline-end: 2px; }

/* ---- fallback: platform cannot compose regional-indicator pairs ---------- */
html.no-flag-emoji .lang-flag__emoji { display: none; }
html.no-flag-emoji .lang-flag {
  display: inline-block;
  /* 1.38 x 0.92em is exactly 3:2, the box every flag below is drawn into, so
     the artwork is never stretched. */
  width: 1.38em;
  height: 0.92em;
  vertical-align: -0.11em;
  background-repeat: no-repeat;
  background-position: center;
  background-size: 100% 100%;
  border-radius: 2px;
  /* A hairline keeps the white-edged flags (JP, ID, RU) from bleeding into a
     light background. Inset so it never changes the box size. */
  box-shadow: inset 0 0 0 0.5px rgba(0, 0, 0, 0.22);
}
"""


def build():
    rules = []
    for code, name, _dir in LANGUAGES:
        rules.append(
            f"/* {name} */\n"
            f'html.no-flag-emoji .lang-flag--{code} {{ background-image: url("{data_uri(code)}"); }}')
        if code not in FLAG_EMOJI:
            raise SystemExit(
                f"ERROR: no flag emoji for language {code!r}. site_common.LANGUAGES and "
                f"flag_svgs.FLAG_EMOJI have drifted apart; the switcher would render an "
                f"empty box for this language.")
    css = HEAD + "\n" + "\n".join(rules) + "\n"
    CSS_OUT.parent.mkdir(parents=True, exist_ok=True)
    CSS_OUT.write_text(css, encoding="utf-8")
    print(f"wrote {CSS_OUT.relative_to(ROOT)} ({len(css):,} bytes, {len(rules)} flags)")

    js = lang_detect.js_file_source()
    JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    JS_OUT.write_text(js, encoding="utf-8")
    print(f"wrote {JS_OUT.relative_to(ROOT)} ({len(js):,} bytes)")


if __name__ == "__main__":
    build()
