/* GENERATED by scripts/build_lang_assets.py from scripts/lang_detect.py
   and scripts/lang_regions.py - do not edit by hand.

   Entry-time language detection + the flag-emoji capability probe.
   Loaded from the <head> of every page and called immediately with that
   page's own language / section / link table. See scripts/lang_detect.py
   for the resolution order, the anti-loop argument and the SEO note.

   The three tables below are region guesses, not location data: see
   scripts/lang_regions.py for why a static site on GitHub Pages has
   nothing better than the device timezone to go on. */
window.__auroraCorvusLangInit=(function(){
var TZ="ja Tokyo|ko Seoul Pyongyang|zh Shanghai Chongqing Chungking Harbin Urumqi Kashgar Taipei Hong_Kong Macau|id Jakarta Pontianak Makassar Jayapura Kuala_Lumpur Kuching Brunei|tr Istanbul Baku|de Berlin Vienna Zurich Busingen Vaduz|it Rome Vatican San_Marino|fr Paris Monaco Brussels Luxembourg Dakar Abidjan Kinshasa Lubumbashi Bamako Ouagadougou Niamey Conakry Libreville Brazzaville Douala Bangui Ndjamena Porto-Novo Lome Djibouti Antananarivo Reunion Mayotte Martinique Guadeloupe Cayenne Port-au-Prince|es Madrid Canary Ceuta Andorra Mexico_City Cancun Merida Monterrey Chihuahua Hermosillo Mazatlan Tijuana Ojinaga Buenos_Aires Cordoba Mendoza Salta Tucuman Jujuy Bogota Lima Santiago Punta_Arenas Caracas Guatemala Montevideo Asuncion La_Paz Havana Santo_Domingo Costa_Rica Panama Managua Tegucigalpa El_Salvador Guayaquil Galapagos Puerto_Rico Malabo|pt-br Sao_Paulo Bahia Fortaleza Recife Manaus Belem Cuiaba Campo_Grande Porto_Velho Rio_Branco Noronha Maceio Araguaina Santarem Eirunepe Boa_Vista Lisbon Azores Madeira Cape_Verde Luanda Maputo Bissau Sao_Tome|ar Riyadh Dubai Qatar Kuwait Bahrain Muscat Baghdad Amman Beirut Damascus Gaza Hebron Aden Cairo Khartoum Tripoli Tunis Algiers Casablanca El_Aaiun Nouakchott Mogadishu Comoro|ru Moscow Kaliningrad Samara Volgograd Saratov Astrakhan Ulyanovsk Kirov Yekaterinburg Omsk Novosibirsk Krasnoyarsk Irkutsk Yakutsk Vladivostok Magadan Kamchatka Sakhalin Chita Novokuznetsk Barnaul Tomsk Anadyr Khandyga Ust-Nera Srednekolymsk Minsk Almaty Aqtobe Aqtau Atyrau Oral Qostanay Qyzylorda Bishkek Tashkent Samarkand Dushanbe Ashgabat Yerevan Tbilisi|en Kolkata Calcutta Colombo Dhaka Karachi Kathmandu Thimphu Singapore Manila Jerusalem Bangkok Ho_Chi_Minh Phnom_Penh Vientiane Yangon Nicosia Famagusta Kabul Tehran";
var RG="ja JP|ko KR KP|zh CN TW HK MO SG|id ID MY BN|tr TR AZ CY|de DE AT CH LI|it IT SM VA|fr FR BE LU MC SN CI CD CM ML BF NE GN GA CG TD BJ TG MG RE HT DJ|es ES MX AR CO PE CL VE GT UY PY BO CU DO CR PA NI HN SV EC PR GQ AD|pt-br BR PT AO MZ CV GW ST TL|ar SA AE QA KW BH OM IQ JO LB SY PS YE EG SD LY TN DZ MA MR SO KM EH|ru RU BY KZ KG UZ TJ TM AM GE|en GB US CA AU NZ IE ZA IN PK BD LK NP PH SG MY NG KE GH TZ UG ZM ZW IL TH VN KH MM JM TT BB BS MT";
var AR="en Europe America Africa Australia Pacific Atlantic Indian";
return function (C) {
  var LANGS = C.l, HREF = C.h, CUR = C.c, SECTION = C.s;
  /* KEY is a contract with assets/js/main.js — grep "aurora-corvus-lang". */
  var KEY = "aurora-corvus-lang", ONCE = "aurora-corvus-lang-redirected";

  var flagW = null;
  function composesFlags() {
    try {
      var cv = document.createElement("canvas");
      if (!cv.getContext) return false;
      var x = cv.getContext("2d");
      if (!x) return false;
      x.font = "32px sans-serif";
      var pair = x.measureText("\uD83C\uDDEF\uD83C\uDDF5").width;  /* JP flag */
      var one = x.measureText("\uD83C\uDDEF").width;               /* lone RI J */
      flagW = { pair: pair, one: one, ratio: one ? pair / one : null };
      if (!pair || !one) return false;
      return pair < one * 1.5;
    } catch (e) { return false; }
  }
  if (!composesFlags()) document.documentElement.classList.add("no-flag-emoji");

  var maps = {};
  function unpack(name, packed) {
    if (!maps[name]) {
      var m = {}, g = packed.split("|"), i, j, p;
      for (i = 0; i < g.length; i++) {
        p = g[i].split(" ");
        for (j = 1; j < p.length; j++) m[p[j]] = p[0];
      }
      maps[name] = m;
    }
    return maps[name];
  }
  function known(c) { return c && LANGS.indexOf(c) >= 0 ? c : null; }

  function fromTag(t) {
    t = String(t || "").toLowerCase().replace(/_/g, "-");
    if (!t) return null;
    if (known(t)) return t;
    var base = t.split("-")[0];
    if (base === "pt") return known("pt-br");
    if (base === "in") base = "id";
    return known(base);
  }
  function fromDevice(tags) {
    for (var i = 0; i < tags.length; i++) {
      var m = fromTag(tags[i]);
      if (m) return m;
    }
    return null;
  }
  function fromRegion(tz, tags) {
    var i, j, m, parts;
    if (tz) {
      parts = String(tz).split("/");
      m = known(unpack("tz", TZ)[parts[parts.length - 1]]);
      if (m) return m;
      m = known(unpack("ar", AR)[parts[0]]);
      if (m) return m;
    }
    for (i = 0; i < tags.length; i++) {
      parts = String(tags[i] || "").replace(/_/g, "-").split("-");
      for (j = 1; j < parts.length; j++) {
        if (parts[j].length === 2) {
          m = known(unpack("rg", RG)[parts[j].toUpperCase()]);
          if (m) return m;
        }
      }
    }
    return null;
  }

  /* Pure function of `env` so it can be driven with mocked inputs. */
  function resolve(env) {
    var stored = known(env.stored);
    if (stored === CUR) return { act: "stay", why: "stored-is-current" };
    if (env.internal) {
      var adopt = (!env.redirected && env.fromLang && env.fromLang !== CUR &&
                   env.fromSection === SECTION) ? CUR : null;
      return { act: "stay", why: "internal-nav", adopt: adopt };
    }
    var want = stored || fromDevice(env.tags || []) ||
               fromRegion(env.tz, env.tags || []);
    if (!want) return { act: "stay", why: "no-signal" };
    if (want === CUR) return { act: "stay", why: "already-correct" };
    return { act: "go", to: want, why: stored ? "stored" : "detected" };
  }

  function lsGet(k) { try { return localStorage.getItem(k); } catch (e) { return null; } }
  function lsSet(k, v) { try { localStorage.setItem(k, v); } catch (e) { } }

  /* Site root derived, not hardcoded: /aurora-corvus/ on Pages, / locally. */
  var here = location.pathname.replace(/index\.html$/, "");
  if (here.charAt(here.length - 1) !== "/") here += "/";
  var tail = (CUR === "ja" ? "" : CUR + "/") + SECTION;
  var base = (tail && here.slice(-tail.length) === tail)
    ? here.slice(0, here.length - tail.length) : here;

  function splitPath(p) {
    p = String(p || "").replace(/index\.html$/, "");
    if (p.charAt(p.length - 1) !== "/") p += "/";
    if (p.indexOf(base) !== 0) return null;
    var rest = p.slice(base.length);
    var i = rest.indexOf("/");
    var head = i < 0 ? "" : rest.slice(0, i);
    if (head && head !== "ja" && LANGS.indexOf(head) >= 0)
      return { lang: head, section: rest.slice(i + 1) };
    return { lang: "ja", section: rest };
  }

  var internal = false, from = null;
  try {
    var ref = document.referrer;
    if (ref && ref.indexOf(location.origin + "/") === 0) {
      internal = true;
      from = splitPath(ref.split("#")[0].split("?")[0].slice(location.origin.length));
    }
  } catch (e) { }

  var nav = window.navigator || {};
  var tags = (nav.languages && nav.languages.length) ? nav.languages
    : (nav.language ? [nav.language] : []);
  var tz = null;
  try { tz = Intl.DateTimeFormat().resolvedOptions().timeZone; } catch (e) { }

  var redirected = false, ssUsable = true;
  try { redirected = !!window.sessionStorage.getItem(ONCE); }
  catch (e) { ssUsable = false; }

  var env = {
    stored: lsGet(KEY), internal: internal, redirected: redirected,
    fromLang: from && from.lang, fromSection: from && from.section,
    tags: tags, tz: tz
  };
  var decision = resolve(env);
  window.__auroraCorvusLang = {
    resolve: resolve, env: env, decision: decision, flagWidths: flagW,
    href: HREF, cur: CUR, section: SECTION, base: base, langs: LANGS
  };

  if (decision.adopt) lsSet(KEY, decision.adopt);
  if (decision.act !== "go") return;
  if (!ssUsable || redirected) return;
  try { window.sessionStorage.setItem(ONCE, "1"); } catch (e) { return; }
  location.replace(HREF[decision.to] + location.search + location.hash);
};
})();
