import type { Viewport } from "next";
import { notFound } from "next/navigation";
import type { ReactNode } from "react";
import { DebugHud } from "@/components/DebugHud";
import { Footer } from "@/components/Footer";
import { Header } from "@/components/Header";
import { Reveal } from "@/components/Reveal";
import { SmoothScroll } from "@/components/SmoothScroll";
import { Experience } from "@/engine/Experience";
import { FRESH } from "@/i18n/fresh";
import { asset, BASE_PATH, isLang, LANG_CODES } from "@/lib/site";
import { langData } from "@/lib/wiki";
import type { Lang } from "@/lib/wiki-types";

export const dynamicParams = false;

export function generateStaticParams(): { lang: Lang }[] {
  return LANG_CODES.map((lang) => ({ lang }));
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#000000",
  colorScheme: "dark",
};

/**
 * Before first paint: mark that scripts run (so reveal animations and WebGL-only elements may
 * hide their resting state), and settle the cheap half of the WebGL verdict at once, so a page
 * that will never draw WebGL shows its posters from the first frame. Experience settles the rest.
 */
const BOOT =
  `(function(){var d=document.documentElement;d.setAttribute("data-js","1");try{var q=new URLSearchParams(location.search),` +
  `n=navigator,c=n.connection;if(q.get("webgl")==="off"||q.get("stage")==="off"||(c&&c.saveData===true)||` +
  `(n.deviceMemory||8)<=2||(n.hardwareConcurrency||8)<=2||!window.WebGL2RenderingContext)d.setAttribute("data-webgl","off")}catch(e){}})();`;

/**
 * Entry-time language detection, exactly as before: the wiki's own detector (portal/lang.js,
 * generated by scripts/build_lang_assets.py) with this page's language table. The section is
 * read from the address because this layout is shared by every page of the language.
 */
function langInit(lang: Lang): string {
  const L = JSON.stringify(LANG_CODES);
  const B = JSON.stringify(`${BASE_PATH}/`);
  const c = JSON.stringify(lang);
  return (
    `(function(){var L=${L},B=${B},c=${c};var p=location.pathname.replace(/index\\.html$/,"");` +
    `if(p.slice(-1)!=="/")p+="/";var r=p.indexOf(B)===0?p.slice(B.length):p.replace(/^\\//,"");` +
    `if(c!=="ja"&&r.indexOf(c+"/")===0)r=r.slice(c.length+1);var h={};` +
    `for(var i=0;i<L.length;i++)h[L[i]]=B+(L[i]==="ja"?"":L[i]+"/")+r;` +
    `window.__auroraCorvusLangInit&&__auroraCorvusLangInit({l:L,h:h,c:c,s:r})})();`
  );
}

export default async function LangLayout({ children, params }: { children: ReactNode; params: Promise<{ lang: string }> }) {
  const { lang } = await params;
  if (!isLang(lang)) notFound();
  const d = langData(lang);
  const f = FRESH[lang];
  const c = d.chrome;
  return (
    <html lang={lang} dir={d.dir} suppressHydrationWarning>
      <head>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script src={asset("lang.js")} />
        <script dangerouslySetInnerHTML={{ __html: langInit(lang) }} />
        <script dangerouslySetInnerHTML={{ __html: BOOT }} />
      </head>
      <body>
        <a className="ac-skip" href="#main">
          {c.skipLink}
        </a>
        <Experience dir={d.dir} />
        <SmoothScroll />
        <Reveal />
        <Header
          lang={lang}
          labels={{
            siteTitle: c.siteTitle,
            home: c.home,
            launcher: c.launcher,
            brands: c.brands,
            recipes: c.recipes,
            changelog: c.changelog,
            upcoming: c.upcoming,
            skin: c.skin,
            discord: c.discord,
            download: c.download,
            menu: c.menu,
            close: c.close,
            language: c.language,
            primary: c.primary,
            sound: f.sound,
            soundOn: f.soundOn,
            soundOff: f.soundOff,
          }}
        />
        <div className="ac-page">
          <main id="main">{children}</main>
          <Footer lang={lang} d={d} />
        </div>
        <DebugHud labels={{ fps: f.debug.fps, drawCalls: f.debug.drawCalls }} />
      </body>
    </html>
  );
}
